Команда `try` - `catch` описывается в функциях чтобы ловить `exceptions` в случае возникновения ошибки.

```php
function findWord($words)

{
    $wordCount = 0;

    foreach ($words as $word) {
        if (gettype($word) != "string") {
            throw new Exception("Isn't a word!");
        }
        $wordCount++;
    }
    echo "$wordCount \n";
}  

try {
    findWord(["It's", "Good", "To", "See", "Ya"]);
    findWord(["Billy", "Jean", "Is", 11, "years"]);
} catch (Exception $error) {
    echo "Exception found: " . $error->getMessage();

}
```

Команда `finally` ставится после catch и выполнится в даже в случае, если поймали `exception`. Полезна для завершения операций, закрытии соединения, сообщения о завершении операции.

```php
function findWord($words)
{
    $wordCount = 0;
  
    foreach ($words as $word) {
        if (gettype($word) != "string") {
            throw new Exception("Isn't a word!");
        }
        
        $wordCount++;
    }
    echo "$wordCount \n";
}

try {
    findWord(["It's", "Good", "To", "See", "Ya"]);
    findWord(["Billy", "Jean", "Is", 11, "years"]);

} catch (Exception $error) {

    echo "Exception found: " . "{$error->getMessage()}\n";
    
} finally {

    echo "The search is complete.";
}
```

Команда `set_exception_handler($callback)` - позволяет выбрать поведение в случае, если поймано исключение.

```php
set_exception_handler('errorMessage');

function findWord($words)
{
    $wordCount = 0;

    foreach ($words as $word) {

        if (gettype($word) != "string") {

            throw new Exception(" $word Isn't a word!");

        }

        $wordCount++;

    }

    echo "$wordCount \n";

}

try {

    findWord(["It's", "Good", "To", "See", "Ya"]);

    findWord(["Billy", "Jean", "Is", 11, "years"]);

} finally {

    echo "Completed search. \n";

}

function errorMessage(Throwable $exception)

{

    echo "Exception found:" . $exception->getMessage();

}
```

Также можно писать кастомные Exception путём имплеминтирования интерфейса `Throwable`, или расширения класса `Exception`.

```php
class SandboxException extends Exception

{
    public function __construct(string $message = "", int $code = 0, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
    }
    public function __toString(): string
    {
        return "Exception found in " . __CLASS__ . ": " . $this->code . $this->message;
    }
    public function printMessage(): string
    {
        return __CLASS__ . " found. " . "Code: " . ($this->code ? $this->code : "no code") . ". Message: " . ($this->message ? $this->message : "no message") . "\n";
    }
}

try {
    if (!isset($statement)) {
        throw new SandboxException("Statement isn't set", 400);
    }
} catch (SandboxException $e) {

    echo $e->printMessage();

} catch (Exception $e) {

    echo $e->getMessage();

} finally {

    echo "Operation closed";

}
```